with-expecter: true
mock-build-tags: "!compile"
inpackage: true
filename: "{{.InterfaceName | snakecase }}_mock.go"
dir: "{{.InterfaceDir}}"
mockname: "Mock{{.InterfaceName}}"
packages:
  github.com/ksysoev/mcp-go-tools/pkg/core:
    interfaces:
      ResourceRepo: {}
  github.com/ksysoev/mcp-go-tools/pkg/api:
    interfaces:
      ToolHandler: {}
